#pragma once

#include <vector>
#include <iostream>
#include <thread>
#include <chrono>
#include <random>
#include <filesystem>
#include <mdspan>
#include <print>
#include <future>
#include <mutex>
#include <functional>
#include <condition_variable>
#include <queue>
#include <utility>
#include <type_traits>
#include <atomic>
#include <memory>
#include <stack>
#include <unordered_set>
#include <unordered_map>
#include <cstdint>
#include <string>
#include <algorithm> 
#include <tuple>